"""`_resolve_yarn_version` reads yarn.lock (yarn v1 and Berry v2+ formats)."""

from __future__ import annotations

from gorget.policy.vendor_constraints import _resolve_yarn_version

YARN_V1 = """\
# THIS IS AN AUTOGENERATED FILE
nanoid@^3.3.6, nanoid@^3.3.7:
  version "3.3.8"
  resolved "https://registry.yarnpkg.com/nanoid/-/nanoid-3.3.8.tgz"

lodash@^4.17.21:
  version "4.17.21"
"""

YARN_BERRY = """\
__metadata:
  version: 8

"nanoid@npm:^3.3.6, nanoid@npm:^3.3.7":
  version: 3.3.8
  resolution: "nanoid@npm:3.3.8"

"@babel/core@npm:^7.20.0":
  version: 7.23.0
  resolution: "@babel/core@npm:7.23.0"
"""


def test_resolves_from_yarn_v1(tmp_path):
    (tmp_path / "yarn.lock").write_text(YARN_V1)
    assert _resolve_yarn_version(tmp_path, "nanoid") == "3.3.8"
    assert _resolve_yarn_version(tmp_path, "lodash") == "4.17.21"


def test_resolves_from_yarn_berry(tmp_path):
    (tmp_path / "yarn.lock").write_text(YARN_BERRY)
    assert _resolve_yarn_version(tmp_path, "nanoid") == "3.3.8"


def test_resolves_scoped_package_berry(tmp_path):
    (tmp_path / "yarn.lock").write_text(YARN_BERRY)
    assert _resolve_yarn_version(tmp_path, "@babel/core") == "7.23.0"


def test_returns_none_when_absent(tmp_path):
    (tmp_path / "yarn.lock").write_text(YARN_BERRY)
    assert _resolve_yarn_version(tmp_path, "not-there") is None


def test_returns_none_without_lockfile(tmp_path):
    assert _resolve_yarn_version(tmp_path, "nanoid") is None


def test_prefix_match_does_not_leak_across_packages(tmp_path):
    # "nano" must not match "nanoid".
    (tmp_path / "yarn.lock").write_text(YARN_V1)
    assert _resolve_yarn_version(tmp_path, "nano") is None


def test_picks_highest_when_multiple_blocks(tmp_path):
    (tmp_path / "yarn.lock").write_text(
        'foo@^1.0.0:\n  version "1.2.0"\n\nfoo@^1.5.0:\n  version "1.5.3"\n'
    )
    assert _resolve_yarn_version(tmp_path, "foo") == "1.5.3"
